---
settings:
  name: GenAI
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de GenAI
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
  - title: Obtén más información sobre el centro de cargas de trabajo de BlueXP  para
      GenAI
    entries:
    - title: Obtén más información sobre el centro de cargas de trabajo de BlueXP 
        para GenAI
      url: "/general/ai-workloads-overview.html"
    - title: Componentes del motor NetApp GenAI
      url: "/general/genai-engine-instance.html"
  - title: Utilice GenAI para crear bases de conocimiento para Amazon Bedrock
    entries:
    - title: Manos a la obra
      entries:
      - title: Inicio rápido
        url: "/knowledge-base/quick-start-knowledge-base.html"
      - title: Requisitos de la base de conocimientos
        url: "/knowledge-base/requirements-knowledge-base.html"
      - title: Identificar orígenes de datos para agregarlos a una base de conocimientos
        url: "/knowledge-base/identify-data-sources-knowledge-base.html"
      - title: Ponga en marcha la infraestructura de GenAI
        url: "/knowledge-base/deploy-infrastructure.html"
    - title: Crear una base de conocimientos
      url: "/knowledge-base/create-knowledgebase.html"
    - title: Pruebe una base de conocimientos
      url: "/knowledge-base/test-knowledgebase.html"
    - title: Active la autenticación
      url: "/knowledge-base/activate-authentication.html"
    - title: Publicar una base de conocimientos
      url: "/knowledge-base/publish-knowledgebase.html"
    - title: Utilice la aplicación de chatbot de ejemplo externo
      url: "/knowledge-base/example-chatbot-application.html"
    - title: Cree una aplicación de IA basada en RAG
      url: "/knowledge-base/create-application.html"
    - title: Lo que puede hacer a continuación
      url: "/knowledge-base/whats-next.html"
  - title: Utilice GenAI para crear conectores para Amazon Q Business
    entries:
    - title: Manos a la obra
      entries:
      - title: Inicio rápido
        url: "/connector/quick-start-connector.html"
      - title: Requisitos del conector
        url: "/connector/requirements-connector.html"
      - title: Identifique orígenes de datos para agregarlos a un conector
        url: "/connector/identify-data-sources-connector.html"
      - title: Ponga en marcha la infraestructura de GenAI
        url: "/connector/deploy-infrastructure.html"
    - title: Cree un conector NetApp ONTAP para Amazon Q
      url: "/connector/define-connector.html"
  - title: Administración y supervisión
    entries:
    - title: Gestione la infraestructura de GenAI
      url: "/general/manage-infrastructure.html"
    - title: Gestionar bases de conocimientos
      url: "/knowledge-base/manage-knowledgebase.html"
    - title: Administrar conectores
      url: "/connector/manage-connector.html"
    - title: Gestionar orígenes de datos
      url: "/general/manage-data-source.html"
    - title: Supervise las operaciones con Tracker
      url: "/general/monitor-operations.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/support-registration.html"
    - title: Resolución de problemas
      url: "/general/troubleshooting.html"
    - title: Obtenga ayuda
      url: "/get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
