---
sidebar: sidebar 
permalink: troubleshooting.html 
keywords: support registration, register for support, support, nss account, add nss account, 
summary: Antes de poder abrir un caso de soporte con el soporte técnico de NetApp, debe añadir una cuenta del sitio de soporte de NetApp a la fábrica de carga de trabajo y, a continuación, registrarse para recibir soporte. 
---
= Resolución de problemas
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aprenda a solucionar algunos problemas comunes que puede encontrar.



== Problemas y soluciones comunes

Si tiene uno de estos problemas, puede seguir los pasos de la columna Solución alternativa para intentar resolverlo.

[cols="1,2,2,4"]
|===
| Zona | Problema | Causa | Solución alternativa 


| Puesta en marcha | La implementación falla porque el volumen ya existe. | La fábrica de cargas de trabajo para GenAI necesita crear un nuevo volumen durante el proceso de implementación, pero ya existe un volumen con el nombre que especificó. | Especifique un nombre único que se utilizará para el nuevo volumen e intente implementar de nuevo. 


| Puesta en marcha | Se produce un error en la implementación porque la fábrica de la carga de trabajo de GenAI no puede montar el volumen. | Uno o más de los puertos de entrada necesarios para FSx para NetApp ONTAP están cerrados o filtrados.  a| 
Abra los puertos enumerados en https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/reference-security-groups-fsx.html#inbound-rules["Reglas de grupo de seguridad para FSX para ONTAP"^].



| Mantenimiento | No se pudo iniciar la instancia de Docker de backend utilizada por la fábrica de carga de trabajo para GenAI. | Se ha suprimido el volumen y se ha reiniciado la instancia de EC2.  a| 
Utilice los siguientes pasos de recuperación:

.Pasos
. Crea un nuevo volumen en FSx para NetApp ONTAP. Por ejemplo, el nombre del volumen puede ser `netapp_ai` y la ruta de volumen puede ser `/netapp_ai`.
. SSH a la instancia de Amazon EC2.
. Enumere los volúmenes:
+
[source, console]
----
docker volume list
----
. Elimine el volumen antiguo:
+
[source, console]
----
docker volume rm ec2-user_persistent_folder
----
. Abra el `docker-compose.yml` archivo con un editor de texto.
. En `volumes` la sección, cambie la ruta del dispositivo a la nueva ruta del volumen. Por ejemplo:
+
[source, yaml]
----
volumes:
  persistent_folder:
    driver_opts:
      type: 'nfs'
      o: "addr=svm-0df66b96a890d8a72.\
      fs-0d673008aaca12bc3.\
      fsx.us-east-1.amazonaws.com,nolock,soft,rw"
      device: ':/netapp_ai' # Path to new volume
----




| Mantenimiento | No se pudo iniciar la instancia de Docker de backend utilizada por la fábrica de carga de trabajo para GenAI. | Se eliminó el volumen raíz. | Cree un volumen con un nombre y una ruta y, a continuación, reinicie la instancia de Docker back-end desde Amazon EC2. 
|===