---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Descubra las novedades de la funcionalidad de las cargas de trabajo de IA de fábrica de cargas de trabajo. 
---
= Novedades del centro de cargas de trabajo BlueXP  para GenAI
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubra las novedades de la funcionalidad para cargas de trabajo de IA generativas de la fábrica de cargas de trabajo.



== 01 de diciembre de 2024



=== Clone una base de conocimientos desde una copia de Snapshot

La fábrica de cargas de trabajo de BlueXP  para GenAI ahora admite la clonación de una base de conocimientos a partir de una copia Snapshot. Esto permite una rápida recuperación de las bases de conocimiento y la creación de nuevas bases de conocimiento con las fuentes de datos existentes, y ayuda con la recuperación y el desarrollo de datos.

link:https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#clone-a-knowledge-base["Clonar una base de conocimientos"]



=== Detección y replicación de clústeres de ONTAP en las instalaciones

Detecta y replica los datos de los clústeres de ONTAP on-premises en un sistema de archivos FSx para ONTAP para que se puedan utilizar para enriquecer las bases de conocimientos de IA. Todos los flujos de trabajo de descubrimiento y replicación en las instalaciones son posibles desde la nueva pestaña *ONTAP local* en el inventario de almacenamiento.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/use-onprem-data.html["Detectar un clúster de ONTAP en las instalaciones"]



== 3 de noviembre de 2024



=== Enmascarar la información de identificación personal con barreras de datos

La carga de trabajo de IA generativa presenta la función de barreras de datos impulsada por la clasificación de BlueXP . La función de barandas de datos identifica y enmascara la información personal identificable (PII), lo que le ayuda a mantener el cumplimiento y reforzar la seguridad de los datos confidenciales de su organización.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#create-and-configure-the-knowledge-base["Crear una base de conocimientos"]

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Más información sobre la clasificación de BlueXP"^]



== 29 de septiembre de 2024



=== Compatibilidad con Snapshot y restauración para volúmenes de base de conocimientos

Ahora puede proteger los datos de las cargas de trabajo de IA generativas con una copia puntual de una base de conocimientos. Esto le permite proteger los datos contra la pérdida accidental o cambios de pruebas en la configuración de la base de conocimientos. Puede restaurar la versión anterior del volumen de la base de conocimientos en cualquier momento.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#take-a-snapshot-of-a-knowledge-base-volume["Tomar una copia Snapshot de un volumen de base de conocimientos"]

https://review.docs.netapp.com/us-en/workload-genai_29-sept-24-release/manage-knowledgebase.html#restore-a-snapshot-of-a-knowledge-base-volume["Restaure una copia Snapshot de un volumen de base de conocimientos"]



=== Pausar secuencias programadas

Ahora puede pausar las exploraciones de orígenes de datos programadas. De forma predeterminada, las cargas de trabajo de IA generativas analizan cada origen de datos diariamente para incorporar datos nuevos en cada base de conocimientos. Si no desea que se ingieran los cambios más recientes (durante la prueba o al restaurar una instantánea, por ejemplo), puede pausar las exploraciones programadas y reanudarlas en cualquier momento.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html["Gestionar bases de conocimientos"]



=== Volúmenes de protección de datos ahora compatibles con las bases de conocimientos

Cuando se selecciona un volumen de base de conocimientos, ahora se puede elegir un volumen de protección de datos que forme parte de una relación de replicación de NetApp SnapMirror. Esto permite almacenar bases de conocimientos en volúmenes que ya están protegidos por la replicación de SnapMirror.

https://docs.netapp.com/us-en/workload-genai/identify-data-sources.html["Identifique las fuentes de datos que desea integrar en su base de conocimientos"]



== 1 de septiembre de 2024



=== Estrategias de fragmentación adicionales

Las cargas de trabajo de IA generativas ahora admiten la fragmentación de varias frases y la fragmentación basada en superposiciones para los orígenes de datos.



=== Volumen dedicado para cada base de conocimientos

Las cargas de trabajo de IA generativas ahora crean un volumen de Amazon FSx para NetApp ONTAP dedicado para cada nueva base de conocimientos, lo que permite establecer políticas Snapshot individuales para cada base de conocimientos y mejorar la protección contra errores y envenenamientos de datos.



== 4 de agosto de 2024



=== Integración de Amazon CloudWatch Logs

Las cargas de trabajo de IA generativas ahora están integradas con Amazon CloudWatch Logs, lo que le permite supervisar los archivos de registro de las cargas de trabajo de IA generativas.



=== Aplicación de chatbot de ejemplo

La aplicación de muestra GenAI de fábrica de cargas de trabajo de NetApp le permite probar la autenticación y la recuperación de su base de conocimientos de fábrica de cargas de trabajo de NetApp publicada al interactuar directamente con ella en una aplicación de chatbot basada en web.



== 7 de julio de 2024



=== Lanzamiento inicial de la fábrica de cargas de trabajo para GenAI

La versión inicial incluye la capacidad de desarrollar una base de conocimientos personalizada mediante la incorporación de los datos de la organización. La base de conocimientos puede ser accedida por una aplicación de chatbot para sus usuarios. Esta capacidad garantiza respuestas precisas y relevantes a preguntas específicas de la organización, mejorando la satisfacción y la productividad de todos sus usuarios.
