---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Descubra las novedades de la funcionalidad de las cargas de trabajo de IA de fábrica de cargas de trabajo. 
---
= Novedades del centro de cargas de trabajo BlueXP  para GenAI
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubra las novedades de la funcionalidad para cargas de trabajo de IA generativas de la fábrica de cargas de trabajo.



== 02 de febrero de 2025



=== Compatibilidad con los modelos de base de Amazon Nova

GenAI ahora es compatible con los modelos básicos de Amazon Nova. Amazon Nova Micro, Amazon Nova Lite y Amazon Nova Pro son compatibles.

link:https://docs.netapp.com/us-en/workload-genai/requirements.html["Requisitos de GenAI"]



=== Filtrado de tipo de archivo para orígenes de datos

GenAI ahora admite la selección de tipos de archivo específicos para incluir en el análisis de origen de datos al agregar un origen de datos.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Agregue orígenes de datos a la base de conocimientos"]



=== Filtrado de fecha de modificación de archivo para orígenes de datos

GenAI ahora admite el filtrado de archivos para incluirlos en el análisis de origen de datos por fecha de modificación al agregar un origen de datos. Puede elegir un rango de fechas de modificación para los archivos incluidos.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Agregue orígenes de datos a la base de conocimientos"]



=== Soporte para archivos de imagen y soporte mejorado para archivos PDF

GenAI ahora admite el escaneo de archivos de imagen e imágenes dentro de archivos PDF (también conocido como soporte de archivos multimodal). Si elige archivos de imagen, el texto de las imágenes se escanea en el origen de datos y se utiliza como datos. Esta función incluye imágenes en documentos PDF; si incluye tipos de archivos PDF, las imágenes de cada PDF se escanean en busca de texto y ese texto se incluye en la información de la fuente de datos.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Agregue orígenes de datos a la base de conocimientos"]



=== Soporte híbrido de búsqueda y reselección

GenAI ahora mejora la relevancia de los resultados de búsqueda mediante el uso de la búsqueda híbrida y la re-clasificación de los resultados. La búsqueda híbrida combina búsquedas de palabras clave con búsquedas vectoriales y semánticas. Los resultados de búsqueda de palabras clave estándar se aumentan con coincidencias cercanas y matices lingüísticos, lo que mejora la relevancia. GenAI vuelve a clasificar los resultados de búsqueda y solo devuelve los resultados con la mayor relevancia.

link:https://docs.netapp.com/us-en/workload-genai/ai-workloads-overview.html#benefits-of-using-genai-to-create-generative-ai-applications["Obtén más información sobre el centro de cargas de trabajo de BlueXP  para GenAI"]



== 05 de enero de 2025



=== Nombre de snapshot personalizado

Ahora es posible proporcionar un nombre de snapshot para una snapshot ad-hoc.

link:https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#protect-a-knowledge-base-with-snapshots["Proteger una base de conocimientos con instantáneas"]



=== Nombre de instancia de motor AI personalizado

Ahora puede asignar un nombre personalizado a la instancia del motor de AI durante la implementación.

link:https://docs.netapp.com/us-en/workload-genai/deploy-infrastructure.html["Ponga en marcha la infraestructura de GenAI"]



=== Reconstruir la infraestructura de GenAI dañada o faltante

Si su instancia de motor de IA se daña o se elimina de alguna manera, puede dejar que la fábrica de cargas de trabajo la reconstruya por usted. La fábrica de cargas de trabajo vuelve a conectar automáticamente sus bases de conocimientos a la infraestructura una vez finalizada la reconstrucción, de modo que estén listas para su uso.

link:https://docs.netapp.com/us-en/workload-genai/troubleshooting.html["Resolución de problemas"]



== 01 de diciembre de 2024



=== Clone una base de conocimientos desde una copia de Snapshot

La fábrica de cargas de trabajo de BlueXP  para GenAI ahora admite la clonación de una base de conocimientos a partir de una copia Snapshot. Esto permite una rápida recuperación de las bases de conocimiento y la creación de nuevas bases de conocimiento con las fuentes de datos existentes, y ayuda con la recuperación y el desarrollo de datos.

link:https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#clone-a-knowledge-base["Clonar una base de conocimientos"]



=== Detección y replicación de clústeres de ONTAP en las instalaciones

Detecta y replica los datos de los clústeres de ONTAP on-premises en un sistema de archivos FSx para ONTAP para que se puedan utilizar para enriquecer las bases de conocimientos de IA. Todos los flujos de trabajo de descubrimiento y replicación en las instalaciones son posibles desde la nueva pestaña *ONTAP local* en el inventario de almacenamiento.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/use-onprem-data.html["Detectar un clúster de ONTAP en las instalaciones"]



== 3 de noviembre de 2024



=== Enmascarar la información de identificación personal con barreras de datos

La carga de trabajo de IA generativa presenta la función de barreras de datos impulsada por la clasificación de BlueXP . La función de barandas de datos identifica y enmascara la información personal identificable (PII), lo que le ayuda a mantener el cumplimiento y reforzar la seguridad de los datos confidenciales de su organización.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#create-and-configure-the-knowledge-base["Crear una base de conocimientos"]

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Más información sobre la clasificación de BlueXP"^]



== 29 de septiembre de 2024



=== Compatibilidad con Snapshot y restauración para volúmenes de base de conocimientos

Ahora puede proteger los datos de las cargas de trabajo de IA generativas con una copia puntual de una base de conocimientos. Esto le permite proteger los datos contra la pérdida accidental o cambios de pruebas en la configuración de la base de conocimientos. Puede restaurar la versión anterior del volumen de la base de conocimientos en cualquier momento.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#take-a-snapshot-of-a-knowledge-base-volume["Tomar una copia Snapshot de un volumen de base de conocimientos"]

https://review.docs.netapp.com/us-en/workload-genai_29-sept-24-release/manage-knowledgebase.html#restore-a-snapshot-of-a-knowledge-base-volume["Restaure una copia Snapshot de un volumen de base de conocimientos"]



=== Pausar secuencias programadas

Ahora puede pausar las exploraciones de orígenes de datos programadas. De forma predeterminada, las cargas de trabajo de IA generativas analizan cada origen de datos diariamente para incorporar datos nuevos en cada base de conocimientos. Si no desea que se ingieran los cambios más recientes (durante la prueba o al restaurar una instantánea, por ejemplo), puede pausar las exploraciones programadas y reanudarlas en cualquier momento.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html["Gestionar bases de conocimientos"]



=== Volúmenes de protección de datos ahora compatibles con las bases de conocimientos

Cuando se selecciona un volumen de base de conocimientos, ahora se puede elegir un volumen de protección de datos que forme parte de una relación de replicación de NetApp SnapMirror. Esto permite almacenar bases de conocimientos en volúmenes que ya están protegidos por la replicación de SnapMirror.

https://docs.netapp.com/us-en/workload-genai/identify-data-sources.html["Identifique las fuentes de datos que desea integrar en su base de conocimientos"]



== 1 de septiembre de 2024



=== Estrategias de fragmentación adicionales

Las cargas de trabajo de IA generativas ahora admiten la fragmentación de varias frases y la fragmentación basada en superposiciones para los orígenes de datos.



=== Volumen dedicado para cada base de conocimientos

Las cargas de trabajo de IA generativas ahora crean un volumen de Amazon FSx para NetApp ONTAP dedicado para cada nueva base de conocimientos, lo que permite establecer políticas Snapshot individuales para cada base de conocimientos y mejorar la protección contra errores y envenenamientos de datos.



== 4 de agosto de 2024



=== Integración de Amazon CloudWatch Logs

Las cargas de trabajo de IA generativas ahora están integradas con Amazon CloudWatch Logs, lo que le permite supervisar los archivos de registro de las cargas de trabajo de IA generativas.



=== Aplicación de chatbot de ejemplo

La aplicación de muestra GenAI de fábrica de cargas de trabajo de NetApp le permite probar la autenticación y la recuperación de su base de conocimientos de fábrica de cargas de trabajo de NetApp publicada al interactuar directamente con ella en una aplicación de chatbot basada en web.



== 7 de julio de 2024



=== Lanzamiento inicial de la fábrica de cargas de trabajo para GenAI

La versión inicial incluye la capacidad de desarrollar una base de conocimientos personalizada mediante la incorporación de los datos de la organización. La base de conocimientos puede ser accedida por una aplicación de chatbot para sus usuarios. Esta capacidad garantiza respuestas precisas y relevantes a preguntas específicas de la organización, mejorando la satisfacción y la productividad de todos sus usuarios.
