---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Descubra las novedades de la funcionalidad de cargas de trabajo de IA de Workload Factory. 
---
= Lo nuevo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubra las novedades de la funcionalidad de cargas de trabajo de IA generativas de Workload Factory.



== 1 de septiembre de 2024



=== Estrategias de fragmentación adicionales

Las cargas de trabajo de IA generativas ahora admiten la fragmentación de varias frases y la fragmentación basada en superposiciones para los orígenes de datos.



=== Volumen dedicado para cada base de conocimientos

Las cargas de trabajo de IA generativas ahora crean un volumen de Amazon FSx para NetApp ONTAP dedicado para cada nueva base de conocimientos, lo que permite establecer políticas Snapshot individuales para cada base de conocimientos y mejorar la protección contra errores y envenenamientos de datos.



== 4 de agosto de 2024



=== Integración de Amazon CloudWatch Logs

Las cargas de trabajo de IA generativas ahora están integradas con Amazon CloudWatch Logs, lo que le permite supervisar los archivos de registro de las cargas de trabajo de IA generativas.



=== Aplicación de chatbot de ejemplo

La aplicación de muestra de GenAI de Fábrica de Carga de Trabajo de NetApp le permite probar la autenticación y la recuperación de su base de conocimientos publicada de Fábrica de Carga de Trabajo de NetApp al interactuar directamente con ella en una aplicación de chatbot basada en web.



== 7 de julio de 2024



=== Lanzamiento inicial de Workload Factory para GenAI

La versión inicial incluye la capacidad de desarrollar una base de conocimientos personalizada mediante la incorporación de los datos de la organización. La base de conocimientos puede ser accedida por una aplicación de chatbot para sus usuarios. Esta capacidad garantiza respuestas precisas y relevantes a preguntas específicas de la organización, mejorando la satisfacción y la productividad de todos sus usuarios.
