= Clone una base de conocimientos desde una copia de Snapshot
:allow-uri-read: 




=== Clone una base de conocimientos desde una copia de Snapshot

NetApp Workload Factory para GenAI ahora admite la clonación de una base de conocimiento a partir de una instantánea.  Esto permite la recuperación rápida de bases de conocimiento y la creación de nuevas bases de conocimiento con fuentes de datos existentes, y ayuda con la recuperación y el desarrollo de datos.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#clone-a-knowledge-base["Clonar una base de conocimientos"]



=== Detección y replicación de clústeres de ONTAP en las instalaciones

Descubra y replique datos del clúster ONTAP local en un sistema de archivos FSx para ONTAP para que puedan usarse para enriquecer las bases de conocimiento de IA.  Todos los flujos de trabajo de descubrimiento y replicación locales son posibles desde el nuevo menú *On-Premises ONTAP* en el inventario de almacenamiento.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/use-onprem-data.html["Detectar un clúster de ONTAP en las instalaciones"]
